In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
sent=("휴일이 오늘도 서쪽을 중심으로 폭염이 이어졌는데요, 내일 은 반가운 비 소식이 있습니다." ,"폭염을 피해서 휴일에 놀러왔다가 갑작스런 비로인해 망연자실 하고 있습니다.")
tfidf_vectorizer=TfidfVectorizer()
tfidf_matrix=tfidf_vectorizer.fit_transform(sent) #문장 벡터화 진행

idf=tfidf_vectorizer.idf_
print(dict(zip(tfidf_vectorizer.get_feature_names(), idf))) # 각 수치에 대한 값 시각화

{'갑작스런': 1.4054651081081644, '내일': 1.4054651081081644, '놀러왔다가': 1.4054651081081644, '망연자실': 1.4054651081081644, '반가운': 1.4054651081081644, '비로인해': 1.4054651081081644, '서쪽을': 1.4054651081081644, '소식이': 1.4054651081081644, '오늘도': 1.4054651081081644, '이어졌는데요': 1.4054651081081644, '있습니다': 1.0, '중심으로': 1.4054651081081644, '폭염을': 1.4054651081081644, '폭염이': 1.4054651081081644, '피해서': 1.4054651081081644, '하고': 1.4054651081081644, '휴일에': 1.4054651081081644, '휴일이': 1.4054651081081644}


In [5]:
# TF-IDF로 벡터화한 값은 자카도를 제외한 유사도 측정에 모두 사용.

In [6]:
#코사인 유사도

In [8]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(tfidf_matrix[0:1],tfidf_matrix[1:2]) # 첫번째와 두번째비교.


array([[0.05629716]])

In [9]:
#유클리디언 유사도

In [11]:
from sklearn.metrics.pairwise import euclidean_distances

euclidean_distances(tfidf_matrix[0:1],tfidf_matrix[1:2])

array([[1.37382884]])

In [12]:
#유클리디언 유사도  L1 정규화 (0~1)

In [14]:
import numpy as np

def l1_normalize(v):
    norm=np.sum(v)
    return v/norm

tfidf_norm_l1=l1_normalize(tfidf_matrix)
euclidean_distances(tfidf_norm_l1[0:1],tfidf_norm_l1[1:2])

array([[0.22387021]])

In [18]:
#맨하탄 유사도
from sklearn.metrics.pairwise import manhattan_distances

manhattan_distances(tfidf_norm_l1[0:1],tfidf_norm_l1[1:2])

array([[0.92479112]])